name: Publish to Github Pages

on:
  push:
    branches:
      - main


jobs:
  publish:
    runs-on:
      ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Emacs
        run: sudo apt install emacs-nox --yes
      - name: Build the site
        run: ./build.sh
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: public
